apiVersion: v1
kind: Service
metadata:
  name: frontend.service
  namespace: cloudacademy
  labels:
    app: frontend.service
    env: demo
spec:
  ports:
   - protocol: TCP
     port: 80
  selector:
    app: frontend